### ISSUE TITLE
Implement TAP output

### ISSUE THREAD

**Issue by s-oravec** [principal-engineering/pete#33]
http://testanything.org

**Comment by michalpravda** [comment]
It seems to me that this idea has died. Everything I've found looks pretty old(<2010).

**Comment by s-oravec** [comment]
maybe, but some are still alive. still, implementation should be "piece of cake"
- Jenkins plugin https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin

**Comment by s-oravec** [comment]
moved to https://github.com/s-oravec/pete-reporter/issues/2
